# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

curve_fitting_c <- function(xr, yr, minbound, maxbound, equation, control, verbose = TRUE) {
    .Call(`_MetaProfiler_curve_fitting_c`, xr, yr, minbound, maxbound, equation, control, verbose)
}

curve_fitting_test_c <- function(xr, yr, minbound, maxbound, equation, control, verbose = TRUE) {
    .Call(`_MetaProfiler_curve_fitting_test_c`, xr, yr, minbound, maxbound, equation, control, verbose)
}

read_fasta <- function(files, proteins) {
    .Call(`_MetaProfiler_read_fasta`, files, proteins)
}

modify_fasta <- function(db, proteins, filename) {
    invisible(.Call(`_MetaProfiler_modify_fasta`, db, proteins, filename))
}

trypsin_digestion <- function(files, missed_cleavage, min_length, max_length) {
    invisible(.Call(`_MetaProfiler_trypsin_digestion`, files, missed_cleavage, min_length, max_length))
}

qtclust_c <- function(m, n_groups, id, groups, radius, method, start, end, element_wise, verbose = FALSE) {
    .Call(`_MetaProfiler_qtclust_c`, m, n_groups, id, groups, radius, method, start, end, element_wise, verbose)
}

razor <- function(x, id, verbose = TRUE) {
    .Call(`_MetaProfiler_razor`, x, id, verbose)
}

rcpp_hello_world <- function() {
    .Call(`_MetaProfiler_rcpp_hello_world`)
}

